server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: June010622
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SD
mybatis-plus:
    mapper-location: classpath*:/mapper/*Mapper.xml
    type-aliases-package: com.June.Common.pojo
logging:
  level:
    com.June.Orders.mapper: debug
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
