spring:
  application:
    name: common
  redis:
    host: localhost
    port: 6379
    database: 6
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: June010622