server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_goods?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: June010622
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: goodsservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SD
  redis:
    host: localhost
    port: 6379
    database: 6
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: June010622
mybatis-plus:
    mapper-location: classpath*:/mapper/*Mapper.xml
    type-aliases-package: com.June.Common.pojo
logging:
  level:
    com.June.Goods.mapper: debug
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50