server:
  port: 10010
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
    database: 6
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: June010622
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SD
    gateway:
      routes:
        - id: user-service/toLogin
          uri: lb://userservice
          predicates:
            - Path=/User/toLogin/**
          filters:
            - AddRequestHeader=tokenuseless,true
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/User/**
        - id: goods-service/getGoodsDetail
          uri: lb://goodsservice
          predicates:
            - Path=/Goods/getGoodsDetail/**
            - Path=/Goods/getGoodsByUserId/**
          filters:
            - AddRequestHeader=tokenuseless,true
        - id: goodsservice/
          uri: lb://goodsservice
          predicates:
            - Path=/Goods/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/Order/**
        - id: admin-service
          uri: lb://adminservice
          predicates:
            - Path=/Admin/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:8081"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
